CREATE TABLE IF NOT EXISTS public.strategies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_type VARCHAR(16) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description TEXT,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    is_custom BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.strategies ALTER COLUMN strategy_type SET NOT NULL;
ALTER TABLE public.strategies ALTER COLUMN name SET NOT NULL;
ALTER TABLE public.strategies ALTER COLUMN is_favorite SET DEFAULT FALSE;
ALTER TABLE public.strategies ALTER COLUMN is_custom SET DEFAULT FALSE;
ALTER TABLE public.strategies ALTER COLUMN enabled SET DEFAULT TRUE;
ALTER TABLE public.strategies ALTER COLUMN snapshot SET DEFAULT '{}'::jsonb;
ALTER TABLE public.strategies ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE public.strategies ALTER COLUMN updated_at SET DEFAULT NOW();

UPDATE public.strategies SET is_favorite = FALSE WHERE is_favorite IS NULL;
UPDATE public.strategies SET is_custom = FALSE WHERE is_custom IS NULL;
UPDATE public.strategies SET enabled = TRUE WHERE enabled IS NULL;
UPDATE public.strategies SET snapshot = '{}'::jsonb WHERE snapshot IS NULL;
UPDATE public.strategies SET created_at = NOW() WHERE created_at IS NULL;
UPDATE public.strategies SET updated_at = NOW() WHERE updated_at IS NULL;
DELETE FROM public.strategies WHERE strategy_type <> 'select';

ALTER TABLE public.strategies ALTER COLUMN is_favorite SET NOT NULL;
ALTER TABLE public.strategies ALTER COLUMN is_custom SET NOT NULL;
ALTER TABLE public.strategies ALTER COLUMN enabled SET NOT NULL;
ALTER TABLE public.strategies ALTER COLUMN snapshot SET NOT NULL;
ALTER TABLE public.strategies ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE public.strategies ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'strategies_strategy_type_check'
    ) THEN
        ALTER TABLE public.strategies
        DROP CONSTRAINT strategies_strategy_type_check;
    END IF;

    ALTER TABLE public.strategies
    ADD CONSTRAINT strategies_strategy_type_check
    CHECK (strategy_type = 'select');
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'strategies_snapshot_object_check'
    ) THEN
        ALTER TABLE public.strategies
        ADD CONSTRAINT strategies_snapshot_object_check
        CHECK (jsonb_typeof(snapshot) = 'object');
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_strategies_type_enabled
ON public.strategies (strategy_type, enabled, id);

CREATE INDEX IF NOT EXISTS idx_strategies_type_favorite
ON public.strategies (strategy_type, is_favorite, id);

CREATE INDEX IF NOT EXISTS idx_strategies_snapshot_gin
ON public.strategies
USING GIN (snapshot);
