from __future__ import annotations

import hashlib
import hmac
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any

from fastapi import Depends, Header, HTTPException

from app.db import get_conn

TOKEN_DAYS = 30
ROLE_USER = "user"
ROLE_ADMIN = "admin"


def _hash_password(password: str, salt: str | None = None) -> tuple[str, str]:
    if salt is None:
        salt = secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), 120_000)
    return salt, digest.hex()


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def ensure_auth_tables() -> None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(64) NOT NULL UNIQUE,
                    role VARCHAR(16) NOT NULL DEFAULT 'user',
                    password_salt VARCHAR(64) NOT NULL,
                    password_hash VARCHAR(128) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(16) NOT NULL DEFAULT 'user'")
            cur.execute("UPDATE users SET role = %s WHERE role IS NULL OR role = ''", (ROLE_USER,))
            cur.execute(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'users_role_check'
                    ) THEN
                        ALTER TABLE users
                        DROP CONSTRAINT users_role_check;
                    END IF;

                    ALTER TABLE users
                    ADD CONSTRAINT users_role_check
                    CHECK (role IN ('user', 'admin'));
                END $$;
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS user_sessions (
                    token_hash VARCHAR(128) PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    expires_at TIMESTAMPTZ NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute("CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions (user_id)")
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS user_default_state (
                    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                    initialized_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
        conn.commit()


def _initial_role(cur) -> str:
    cur.execute("SELECT COUNT(*) AS count FROM users")
    row = cur.fetchone()
    if not row or not row["count"]:
        return ROLE_ADMIN
    return ROLE_USER


def create_user(username: str, password: str) -> dict[str, Any]:
    username = str(username or "").strip()
    password = str(password or "")
    if len(username) < 3:
        raise ValueError("username must be at least 3 characters")
    if len(password) < 6:
        raise ValueError("password must be at least 6 characters")

    salt, password_hash = _hash_password(password)
    ensure_auth_tables()
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM users WHERE username = %s", (username,))
            if cur.fetchone():
                raise FileExistsError("username already exists")
            role = _initial_role(cur)
            cur.execute(
                """
                INSERT INTO users (username, role, password_salt, password_hash, created_at, updated_at)
                VALUES (%s, %s, %s, %s, NOW(), NOW())
                RETURNING id, username, role, created_at
                """,
                (username, role, salt, password_hash),
            )
            row = cur.fetchone()
        conn.commit()
    initialize_user_defaults(row["id"])
    return _map_user(row)


def initialize_user_defaults(user_id: int | None) -> None:
    if user_id is None:
        return
    ensure_auth_tables()
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM user_default_state WHERE user_id = %s", (user_id,))
            if cur.fetchone():
                return

    from app.concept_service import ensure_user_default_concept_favorites
    from app.strategy_service import ensure_user_default_strategy_favorites

    ensure_user_default_concept_favorites(user_id)
    ensure_user_default_strategy_favorites(user_id)
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO user_default_state (user_id)
                VALUES (%s)
                ON CONFLICT (user_id) DO NOTHING
                """,
                (user_id,),
            )
        conn.commit()


def authenticate_user(username: str, password: str) -> dict[str, Any] | None:
    username = str(username or "").strip()
    ensure_auth_tables()
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id, username, role, password_salt, password_hash, created_at FROM users WHERE username = %s",
                (username,),
            )
            row = cur.fetchone()
    if not row:
        return None
    _, digest = _hash_password(str(password or ""), row["password_salt"])
    if not hmac.compare_digest(digest, row["password_hash"]):
        return None
    return _map_user(row)


def update_user_account(
    user_id: int,
    username: str | None = None,
    current_password: str | None = None,
    new_password: str | None = None,
) -> dict[str, Any]:
    ensure_auth_tables()
    username = str(username or "").strip() if username is not None else None
    new_password = str(new_password or "") if new_password is not None else None
    current_password = str(current_password or "") if current_password is not None else None

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id, username, role, password_salt, password_hash, created_at FROM users WHERE id = %s",
                (user_id,),
            )
            current = cur.fetchone()
            if not current:
                raise ValueError("user not found")

            fields: list[str] = []
            params: list[Any] = []

            if username is not None:
                if len(username) < 3:
                    raise ValueError("username must be at least 3 characters")
                if username != current["username"]:
                    cur.execute("SELECT 1 FROM users WHERE username = %s AND id <> %s", (username, user_id))
                    if cur.fetchone():
                        raise FileExistsError("username already exists")
                    fields.append("username = %s")
                    params.append(username)

            if new_password is not None:
                if len(new_password) < 6:
                    raise ValueError("password must be at least 6 characters")
                _, digest = _hash_password(current_password or "", current["password_salt"])
                if not hmac.compare_digest(digest, current["password_hash"]):
                    raise PermissionError("current password is incorrect")
                salt, password_hash = _hash_password(new_password)
                fields.extend(["password_salt = %s", "password_hash = %s"])
                params.extend([salt, password_hash])

            if fields:
                fields.append("updated_at = NOW()")
                params.append(user_id)
                cur.execute(
                    f"""
                    UPDATE users
                    SET {', '.join(fields)}
                    WHERE id = %s
                    RETURNING id, username, role, created_at
                    """,
                    tuple(params),
                )
                row = cur.fetchone()
            else:
                row = current
        conn.commit()
    return _map_user(row)


def create_session(user_id: int) -> str:
    token = secrets.token_urlsafe(32)
    expires_at = datetime.now(timezone.utc) + timedelta(days=TOKEN_DAYS)
    ensure_auth_tables()
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO user_sessions (token_hash, user_id, expires_at, created_at)
                VALUES (%s, %s, %s, NOW())
                """,
                (_hash_token(token), user_id, expires_at),
            )
        conn.commit()
    return token


def delete_session(token: str) -> None:
    if not token:
        return
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM user_sessions WHERE token_hash = %s", (_hash_token(token),))
        conn.commit()


def user_by_token(token: str | None) -> dict[str, Any] | None:
    if not token:
        return None
    ensure_auth_tables()
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT u.id, u.username, u.role, u.created_at
                FROM user_sessions s
                JOIN users u ON u.id = s.user_id
                WHERE s.token_hash = %s AND s.expires_at > NOW()
                """,
                (_hash_token(token),),
            )
            row = cur.fetchone()
    if row:
        initialize_user_defaults(row["id"])
    return _map_user(row) if row else None


def _bearer_token(authorization: str | None) -> str:
    text = str(authorization or "").strip()
    if text.lower().startswith("bearer "):
        return text[7:].strip()
    return text


def optional_current_user(authorization: str | None = Header(default=None)) -> dict[str, Any] | None:
    return user_by_token(_bearer_token(authorization))


def require_current_user(user: dict[str, Any] | None = Depends(optional_current_user)) -> dict[str, Any]:
    if not user:
        raise HTTPException(status_code=401, detail="please login first")
    return user


def require_admin(user: dict[str, Any] = Depends(require_current_user)) -> dict[str, Any]:
    if user.get("role") != ROLE_ADMIN:
        raise HTTPException(status_code=403, detail="admin access required")
    return user


def _map_user(row: dict[str, Any] | None) -> dict[str, Any]:
    if not row:
        return {}
    created_at = row.get("created_at")
    return {
        "id": row["id"],
        "username": row["username"],
        "role": row.get("role") or ROLE_USER,
        "createdAt": int(created_at.timestamp() * 1000) if created_at else None,
    }
