from datetime import datetime, timezone
from typing import Any

from app.db import get_conn


def ensure_operation_log_table() -> None:
    """确保操作日志表存在"""
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS operation_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT,
                    username VARCHAR(64),
                    role VARCHAR(16),
                    action VARCHAR(32) NOT NULL,
                    resource VARCHAR(64),
                    resource_id VARCHAR(128),
                    details TEXT,
                    ip VARCHAR(45),
                    user_agent TEXT,
                    result VARCHAR(16) DEFAULT 'success',
                    error_message TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            # 创建索引
            cur.execute("CREATE INDEX IF NOT EXISTS idx_operation_logs_user_id ON operation_logs (user_id)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_operation_logs_action ON operation_logs (action)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_operation_logs_resource ON operation_logs (resource)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_operation_logs_created_at ON operation_logs (created_at)")
        conn.commit()


def log_operation(
    user_id: int | None = None,
    username: str | None = None,
    role: str | None = None,
    action: str = "",
    resource: str | None = None,
    resource_id: str | None = None,
    details: str | None = None,
    ip: str | None = None,
    user_agent: str | None = None,
    result: str = "success",
    error_message: str | None = None,
) -> None:
    """记录操作日志"""
    ensure_operation_log_table()
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO operation_logs (
                    user_id, username, role, action, resource, resource_id,
                    details, ip, user_agent, result, error_message, created_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW())
                """,
                (
                    user_id,
                    username,
                    role,
                    action,
                    resource,
                    resource_id,
                    details,
                    ip,
                    user_agent,
                    result,
                    error_message,
                ),
            )
        conn.commit()


def fetch_operation_logs(
    user_id: int | None = None,
    action: str | None = None,
    resource: str | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[dict[str, Any]]:
    """获取操作日志"""
    ensure_operation_log_table()

    conditions = []
    params = []

    if user_id is not None:
        conditions.append("user_id = %s")
        params.append(user_id)

    if action:
        conditions.append("action = %s")
        params.append(action)

    if resource:
        conditions.append("resource = %s")
        params.append(resource)

    where_clause = ""
    if conditions:
        where_clause = "WHERE " + " AND ".join(conditions)

    params.extend([limit, offset])

    sql = f"""
        SELECT
            id, user_id, username, role, action, resource, resource_id,
            details, ip, user_agent, result, error_message, created_at
        FROM operation_logs
        {where_clause}
        ORDER BY created_at DESC
        LIMIT %s OFFSET %s
    """

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, tuple(params))
            rows = cur.fetchall()

    return [
        {
            "id": row["id"],
            "userId": row["user_id"],
            "username": row["username"],
            "role": row["role"],
            "action": row["action"],
            "resource": row["resource"],
            "resourceId": row["resource_id"],
            "details": row["details"],
            "ip": row["ip"],
            "userAgent": row["user_agent"],
            "result": row["result"],
            "errorMessage": row["error_message"],
            "timestamp": int(row["created_at"].timestamp() * 1000) if row["created_at"] else None,
        }
        for row in rows
    ]


def get_operation_log_stats() -> dict[str, Any]:
    """获取操作日志统计信息"""
    ensure_operation_log_table()

    with get_conn() as conn:
        with conn.cursor() as cur:
            # 总操作数
            cur.execute("SELECT COUNT(*) as total FROM operation_logs")
            total = cur.fetchone()["total"]

            # 按操作类型统计
            cur.execute(
                """
                SELECT action, COUNT(*) as count
                FROM operation_logs
                GROUP BY action
                ORDER BY count DESC
                """
            )
            by_action = {row["action"]: row["count"] for row in cur.fetchall()}

            # 按资源类型统计
            cur.execute(
                """
                SELECT resource, COUNT(*) as count
                FROM operation_logs
                WHERE resource IS NOT NULL
                GROUP BY resource
                ORDER BY count DESC
                """
            )
            by_resource = {row["resource"]: row["count"] for row in cur.fetchall()}

            # 按结果统计
            cur.execute(
                """
                SELECT result, COUNT(*) as count
                FROM operation_logs
                GROUP BY result
                """
            )
            by_result = {row["result"]: row["count"] for row in cur.fetchall()}

            # 今天的操作数
            cur.execute(
                """
                SELECT COUNT(*) as today_count
                FROM operation_logs
                WHERE DATE(created_at) = CURRENT_DATE
                """
            )
            today_count = cur.fetchone()["today_count"]

    return {
        "total": total,
        "byAction": by_action,
        "byResource": by_resource,
        "byResult": by_result,
        "todayCount": today_count,
    }
