import json
from dataclasses import dataclass
from typing import Any

from app.db import get_conn

DEFAULT_USER_FAVORITE_STRATEGY_IDS = (1001, 1002, 1003)


@dataclass(frozen=True)
class SelectStrategySeed:
    id: int
    name: str
    description: str
    is_favorite: bool
    enabled: bool
    is_custom: bool
    snapshot: dict[str, Any]


DEFAULT_SELECT_STRATEGIES: tuple[SelectStrategySeed, ...] = (
    SelectStrategySeed(
        id=1001,
        name="强势主线",
        description="涨跌幅、涨跌额、成交额综合筛选（Pareto排序）",
        is_favorite=True,
        enabled=True,
        is_custom=False,
        snapshot={
            "scope": "all",
            "searchQuery": "",
            "selectedMetrics": ["change", "changeAmount", "amount"],
            "filters": {
                "minChange": 2,
                "minChangeAmount": 0.1,
                "minAmountY": 10,
                "minUpRatio": 0.55,
            },
        },
    ),
    SelectStrategySeed(
        id=1002,
        name="资金优先",
        description="以涨跌额为核心，兼顾成交额和板块扩散",
        is_favorite=True,
        enabled=True,
        is_custom=False,
        snapshot={
            "scope": "all",
            "searchQuery": "",
            "selectedMetrics": ["changeAmount", "amount", "upRatio"],
            "filters": {
                "minChangeAmount": 0.3,
                "minAmountY": 15,
                "minUpRatio": 0.5,
            },
        },
    ),
    SelectStrategySeed(
        id=1003,
        name="放量上攻",
        description="涨跌幅与成交额共同确认活跃上攻",
        is_favorite=False,
        enabled=True,
        is_custom=False,
        snapshot={
            "scope": "all",
            "searchQuery": "",
            "selectedMetrics": ["change", "amount", "changeAmount"],
            "filters": {
                "minChange": 1,
                "minAmountY": 8,
                "minChangeAmount": 0,
            },
        },
    ),
    SelectStrategySeed(
        id=1004,
        name="广度确认",
        description="以上涨占比为主，验证板块扩散",
        is_favorite=False,
        enabled=True,
        is_custom=False,
        snapshot={
            "scope": "all",
            "searchQuery": "",
            "selectedMetrics": ["upRatio", "change"],
            "filters": {
                "minUpRatio": 0.65,
                "minChange": 0.5,
            },
        },
    ),
    SelectStrategySeed(
        id=1005,
        name="异动追踪",
        description="短线涨幅与成交额配合，筛选活跃异动概念",
        is_favorite=False,
        enabled=True,
        is_custom=False,
        snapshot={
            "scope": "all",
            "searchQuery": "",
            "selectedMetrics": ["change", "amount", "volatility"],
            "filters": {
                "minChange": 1.5,
                "minAmountY": 6,
            },
        },
    ),
    SelectStrategySeed(
        id=1006,
        name="稳健回撤",
        description="强度不弱 + 波动可控 + 回撤不过深",
        is_favorite=False,
        enabled=True,
        is_custom=False,
        snapshot={
            "scope": "all",
            "searchQuery": "",
            "selectedMetrics": ["change", "amount", "upRatio"],
            "filters": {
                "minChange": 0,
                "minUpRatio": 0.5,
                "maxVolatility": 22,
                "maxDrawdown20d": -8,
                "minAmountY": 8,
            },
        },
    ),
    SelectStrategySeed(
        id=1007,
        name="自定义模板",
        description="示例自定义策略，可在编辑中按需调整",
        is_favorite=False,
        enabled=True,
        is_custom=True,
        snapshot={
            "scope": "all",
            "searchQuery": "",
            "selectedMetrics": ["change", "changeAmount", "amount"],
            "filters": {
                "minChange": 1,
                "minChangeAmount": 0,
                "minAmountY": 6,
            },
        },
    ),
)


def ensure_strategies_table() -> None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            # 统一把 strategies 表修成当前后端约定的结构，避免手动建表遗漏字段或默认值。
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS strategies (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NULL,
                    strategy_type VARCHAR(16) NOT NULL,
                    name VARCHAR(128) NOT NULL,
                    description TEXT,
                    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
                    is_custom BOOLEAN NOT NULL DEFAULT FALSE,
                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute("ALTER TABLE strategies ADD COLUMN IF NOT EXISTS user_id BIGINT NULL")
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS user_strategy_favorites (
                    user_id BIGINT NOT NULL,
                    strategy_id BIGINT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    PRIMARY KEY (user_id, strategy_id)
                )
                """
            )
            cur.execute("ALTER TABLE strategies ALTER COLUMN strategy_type SET NOT NULL")
            cur.execute("ALTER TABLE strategies ALTER COLUMN name SET NOT NULL")
            cur.execute("ALTER TABLE strategies ALTER COLUMN is_favorite SET DEFAULT FALSE")
            cur.execute("ALTER TABLE strategies ALTER COLUMN is_custom SET DEFAULT FALSE")
            cur.execute("ALTER TABLE strategies ALTER COLUMN enabled SET DEFAULT TRUE")
            cur.execute("ALTER TABLE strategies ALTER COLUMN snapshot SET DEFAULT '{}'::jsonb")
            cur.execute("ALTER TABLE strategies ALTER COLUMN created_at SET DEFAULT NOW()")
            cur.execute("ALTER TABLE strategies ALTER COLUMN updated_at SET DEFAULT NOW()")

            cur.execute("UPDATE strategies SET is_favorite = FALSE WHERE is_favorite IS NULL")
            cur.execute("UPDATE strategies SET is_custom = FALSE WHERE is_custom IS NULL")
            cur.execute("UPDATE strategies SET enabled = TRUE WHERE enabled IS NULL")
            cur.execute("UPDATE strategies SET snapshot = '{}'::jsonb WHERE snapshot IS NULL")
            cur.execute("UPDATE strategies SET created_at = NOW() WHERE created_at IS NULL")
            cur.execute("UPDATE strategies SET updated_at = NOW() WHERE updated_at IS NULL")
            cur.execute("DELETE FROM strategies WHERE strategy_type <> 'select'")

            cur.execute("ALTER TABLE strategies ALTER COLUMN is_favorite SET NOT NULL")
            cur.execute("ALTER TABLE strategies ALTER COLUMN is_custom SET NOT NULL")
            cur.execute("ALTER TABLE strategies ALTER COLUMN enabled SET NOT NULL")
            cur.execute("ALTER TABLE strategies ALTER COLUMN snapshot SET NOT NULL")
            cur.execute("ALTER TABLE strategies ALTER COLUMN created_at SET NOT NULL")
            cur.execute("ALTER TABLE strategies ALTER COLUMN updated_at SET NOT NULL")

            cur.execute(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'strategies_strategy_type_check'
                    ) THEN
                        ALTER TABLE strategies
                        DROP CONSTRAINT strategies_strategy_type_check;
                    END IF;

                    ALTER TABLE strategies
                    ADD CONSTRAINT strategies_strategy_type_check
                    CHECK (strategy_type = 'select');
                END $$;
                """
            )
            cur.execute(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'strategies_snapshot_object_check'
                    ) THEN
                        ALTER TABLE strategies
                        ADD CONSTRAINT strategies_snapshot_object_check
                        CHECK (jsonb_typeof(snapshot) = 'object');
                    END IF;
                END $$;
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_strategies_type_enabled
                ON strategies (strategy_type, enabled, id)
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_strategies_type_favorite
                ON strategies (strategy_type, is_favorite, id)
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_strategies_snapshot_gin
                ON strategies
                USING GIN (snapshot)
                """
            )
        conn.commit()


def ensure_user_default_strategy_favorites(user_id: int | None) -> None:
    if user_id is None:
        return
    ensure_strategies_table()
    with get_conn() as conn:
        with conn.cursor() as cur:
            for strategy_id in DEFAULT_USER_FAVORITE_STRATEGY_IDS:
                cur.execute(
                    """
                    INSERT INTO user_strategy_favorites (user_id, strategy_id)
                    VALUES (%s, %s)
                    ON CONFLICT (user_id, strategy_id) DO NOTHING
                    """,
                    (user_id, strategy_id),
                )
        conn.commit()


def _dumps_snapshot(snapshot: dict[str, Any] | None) -> str:
    return json.dumps(snapshot or {}, ensure_ascii=False)


def _map_strategy(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": row["id"],
        "name": row["name"],
        "desc": row["description"],
        "isFavorite": row["is_favorite"],
        "enabled": row["enabled"],
        "isCustom": row["is_custom"],
        "snapshot": row["snapshot"],
        "createdAt": int(row["created_at"].timestamp() * 1000) if row["created_at"] else None,
        "updatedAt": int(row["updated_at"].timestamp() * 1000) if row["updated_at"] else None,
    }


def ensure_select_strategies() -> dict[str, int]:
    preset_ids = [strategy.id for strategy in DEFAULT_SELECT_STRATEGIES]
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT COUNT(*) AS count
                FROM strategies
                WHERE strategy_type = 'select' AND id = ANY(%s)
                """,
                (preset_ids,),
            )
            row = cur.fetchone()
            if row and row["count"] == len(DEFAULT_SELECT_STRATEGIES):
                return {"count": row["count"]}
    return bootstrap_select_strategies()


def bootstrap_select_strategies() -> dict[str, int]:
    with get_conn() as conn:
        with conn.cursor() as cur:
            for strategy in DEFAULT_SELECT_STRATEGIES:
                cur.execute(
                    """
                    INSERT INTO strategies (
                        id,
                        strategy_type,
                        name,
                        description,
                        is_favorite,
                        is_custom,
                        enabled,
                        snapshot,
                        created_at,
                        updated_at
                    )
                    VALUES (%s, 'select', %s, %s, %s, %s, %s, %s::jsonb, NOW(), NOW())
                    ON CONFLICT (id) DO UPDATE
                    SET strategy_type = EXCLUDED.strategy_type,
                        name = EXCLUDED.name,
                        description = EXCLUDED.description,
                        is_favorite = EXCLUDED.is_favorite,
                        is_custom = EXCLUDED.is_custom,
                        enabled = EXCLUDED.enabled,
                        snapshot = EXCLUDED.snapshot,
                        updated_at = NOW()
                    """,
                    (
                        strategy.id,
                        strategy.name,
                        strategy.description,
                        strategy.is_favorite,
                        strategy.is_custom,
                        strategy.enabled,
                        _dumps_snapshot(strategy.snapshot),
                    ),
                )
        conn.commit()
    return {"count": len(DEFAULT_SELECT_STRATEGIES)}


def fetch_select_strategies(user_id: int | None = None) -> list[dict[str, Any]]:
    with get_conn() as conn:
        with conn.cursor() as cur:
            if user_id is None:
                cur.execute(
                    """
                    SELECT id, name, description, is_favorite, is_custom, enabled, snapshot, created_at, updated_at
                    FROM strategies
                    WHERE strategy_type = 'select' AND user_id IS NULL
                    ORDER BY is_favorite DESC, is_custom DESC, id ASC
                    """
                )
            else:
                cur.execute(
                    """
                    SELECT
                        s.id,
                        s.name,
                        s.description,
                        CASE
                            WHEN s.user_id IS NULL THEN COALESCE(usf.strategy_id IS NOT NULL, FALSE)
                            ELSE s.is_favorite
                        END AS is_favorite,
                        s.is_custom,
                        s.enabled,
                        s.snapshot,
                        s.created_at,
                        s.updated_at
                    FROM strategies s
                    LEFT JOIN user_strategy_favorites usf
                      ON usf.strategy_id = s.id
                     AND usf.user_id = %s
                    WHERE s.strategy_type = 'select'
                      AND (
                        (s.user_id IS NULL AND s.is_custom = FALSE)
                        OR s.user_id = %s
                      )
                    ORDER BY is_favorite DESC, s.is_custom DESC, s.id ASC
                    """,
                    (user_id, user_id),
                )
            rows = cur.fetchall()
    return [_map_strategy(row) for row in rows]


def fetch_select_strategy(strategy_id: int, user_id: int | None = None) -> dict[str, Any] | None:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, name, description, is_favorite, is_custom, enabled, snapshot, created_at, updated_at
                FROM strategies
                WHERE strategy_type = 'select'
                  AND id = %s
                  AND (user_id IS NULL OR user_id = %s)
                """,
                (strategy_id, user_id),
            )
            row = cur.fetchone()
    return _map_strategy(row) if row else None


def create_select_strategy(payload: dict[str, Any], user_id: int | None = None) -> dict[str, Any]:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO strategies (
                    strategy_type,
                    user_id,
                    name,
                    description,
                    is_favorite,
                    is_custom,
                    enabled,
                    snapshot,
                    created_at,
                    updated_at
                )
                VALUES ('select', %s, %s, %s, %s, %s, %s, %s::jsonb, NOW(), NOW())
                RETURNING id, name, description, is_favorite, is_custom, enabled, snapshot, created_at, updated_at
                """,
                (
                    user_id,
                    payload["name"],
                    payload.get("desc"),
                    payload.get("isFavorite", False),
                    payload.get("isCustom", True),
                    payload.get("enabled", True),
                    _dumps_snapshot(payload.get("snapshot")),
                ),
            )
            row = cur.fetchone()
        conn.commit()
    return _map_strategy(row)


def update_select_strategy(
    strategy_id: int,
    patch: dict[str, Any],
    user_id: int | None = None,
    is_admin: bool = False,
) -> dict[str, Any] | None:
    current = fetch_select_strategy(strategy_id, user_id)
    if not current:
        return None
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT user_id FROM strategies WHERE strategy_type = 'select' AND id = %s", (strategy_id,))
            owner_row = cur.fetchone()
    is_system_strategy = bool(owner_row) and owner_row["user_id"] is None

    if user_id is not None and set(patch.keys()) == {"isFavorite"} and is_system_strategy:
        ensure_strategies_table()
        with get_conn() as conn:
            with conn.cursor() as cur:
                if patch.get("isFavorite"):
                    cur.execute(
                        """
                        INSERT INTO user_strategy_favorites (user_id, strategy_id)
                        VALUES (%s, %s)
                        ON CONFLICT (user_id, strategy_id) DO NOTHING
                        """,
                        (user_id, strategy_id),
                    )
                else:
                    cur.execute(
                        "DELETE FROM user_strategy_favorites WHERE user_id = %s AND strategy_id = %s",
                        (user_id, strategy_id),
                    )
            conn.commit()
        return {**current, "isFavorite": bool(patch.get("isFavorite"))}

    if not is_admin and user_id is not None and is_system_strategy:
        raise PermissionError("system strategy can only be edited by admin")

    merged = {
        "name": patch.get("name", current["name"]),
        "description": patch.get("desc", current["desc"]),
        "is_favorite": patch.get("isFavorite", current["isFavorite"]),
        "is_custom": patch.get("isCustom", current["isCustom"]),
        "enabled": patch.get("enabled", current["enabled"]),
        "snapshot": patch.get("snapshot", current["snapshot"]),
    }

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE strategies
                SET name = %s,
                    description = %s,
                    is_favorite = %s,
                    is_custom = %s,
                    enabled = %s,
                    snapshot = %s::jsonb,
                    updated_at = NOW()
                WHERE strategy_type = 'select' AND id = %s
                  AND (
                    (%s AND user_id IS NULL)
                    OR user_id = %s
                  )
                RETURNING id, name, description, is_favorite, is_custom, enabled, snapshot, created_at, updated_at
                """,
                (
                    merged["name"],
                    merged["description"],
                    merged["is_favorite"],
                    merged["is_custom"],
                    merged["enabled"],
                    _dumps_snapshot(merged["snapshot"]),
                    strategy_id,
                    is_admin,
                    user_id,
                ),
            )
            row = cur.fetchone()
        conn.commit()
    return _map_strategy(row) if row else None


def delete_select_strategy(strategy_id: int, user_id: int | None = None, is_admin: bool = False) -> bool:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                DELETE FROM strategies
                WHERE strategy_type = 'select' AND id = %s
                  AND (
                    (%s AND user_id IS NULL)
                    OR user_id = %s
                  )
                """,
                (strategy_id, is_admin, user_id),
            )
            deleted = cur.rowcount > 0
        conn.commit()
    return deleted
